project:
  type: website

website:
  title: "ISSS608-VAA-T9"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Proposal.qmd
        text: Project Proposal

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

